version: "3"

networks:
  loki:

services:
  loki:
    # image: grafana/loki:2.2.1
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ./configs:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - loki

  promtail:
    # image: grafana/promtail:2.2.1
    image: grafana/promtail:latest
    volumes:
      - ./volumes/log:/var/log
      - ./configs:/etc/promtail 
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki