server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://301132:eyJrIjoiODYxN2VmMWZmMTdiYzkzODcwNTNiZjAzYjE1M2EwNjQ4ZDg5MGMyNSIsIm4iOiJ0aGVtYXRpY19pbWFnZV9nZW5fMjAyMiIsImlkIjo3MjM5NTV9@logs-prod3.grafana.net/api/prom/push
        
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log